### ISSUE TITLE
Question: How to auto sign emails?

### ISSUE THREAD

**Issue by Anachron** [leahneukirchen/mblaze#122]
So I was wondering how do you automatically sign emails (gpg)? I‘m new to email signing so that idea may be stupid... just let me know how you handle email signing. I am not sending emails with a lot of people so I guess there would be no problem sending my key to those I communicate to so all my emails can be signed by default.

Thanks and have a great day!

**Comment by chneukirchen** [comment]
This is not implemented yet, but should not be hard.

**Comment by Anachron** [comment]
I‘m not even sure how to deal with this. It could be a config entry which gets checked on mcom, but on the other hand mgpg is user contributed, a shell script and checking the config on every mcom call looks like a big overhead.

I however could see a MBLAZE_AUTOSIGN env variable to come in handy here.

**Comment by Anachron** [comment]
So I gave this idea another thought and came to a pretty quick but still dynamic solution.

My proposal: Check whether MBLAZE_AUTOSIGN is set. If it is, do the following: 
- Env is set to 0/1: Either auto sign all or none of the emails
- Env is alphanumeric: Try to execute this command on the system (passing the email as param) and check RC being 0. If true, auto sign the email.

This way we can write as complex or simplistic logic for auto signing as we need. 

Another idea would be to completely decouple this from the signing idea and call it MBLAZE_AUTOCMD and let the user handle arbitary commands automatically once the email is written. This would allow for so much more use-cases like auto-attaching signatures depending on receiver, checking for attachments and adding privacy statements etc.

Let me know what you think!

**Comment by Anachron** [comment]
@chneukirchen what's your opinion about my last post?

**Comment by Valodim** [comment]
Slightly related to this, I wrote a piece on why pgp-signing mails by default is [counterproductive for the ecosystem](https://k9mail.github.io/2016/11/24/OpenPGP-Considerations-Part-I.html) a while ago, and why I decided to remove the feature from K-9 Mail.

**Comment by chneukirchen** [comment]
Thanks. The crypto stuff so far is pretty much bolted on, and not very well tested; essentially it has to features for me to deal with other's encrypted/signed mail.

I'll definitely be wary of making it a default, and it certainly needs more review.

**Comment by Anachron** [comment]
I think the scope of this feature has widened. We're not talking about gpg-encrypt anymore but rather a general way how to hook mblaze with other tools to allow for better integration and easier workflows for the users. 

While I do agree that gpg encrypted emails do not change a thing when you have  other communications which are unencrypted with the same person, but I can definitely sleep better knowing my emails are not easily "catchable" from middle-men as they are now.

**Comment by chneukirchen** [comment]
Nope, sorry. You'll need to build yourself something, I won't get around to it soon.

**Comment by Anachron** [comment]
Closing for now as I have currently no interest in `gpg` encryption.
