### ISSUE TITLE
pledge()

### ISSUE THREAD

**Issue by bentley** [leahneukirchen/mblaze#151]
Mail is one of the major sources of untrusted input on my system. It would be nice to start dropping privileges in the various programs with [pledge(2)](https://man.openbsd.org/pledge.2).

**Comment by chneukirchen** [comment]
Feel free to help with https://github.com/chneukirchen/mblaze/pull/79

I don't use OpenBSD for reading mail, so this will take someone else to work on.

**Comment by ndalliard** [comment]
Can be closed cause #179
