### ISSUE TITLE
mcom(1): do_mime portability on macOS

### ISSUE THREAD

**Issue by silby** [leahneukirchen/mblaze#162]
mcom(1)'s do_mime calls `file -Lbi` to get a mime-type for a file to be attached. On macOS, the `-i` option to the vendor's `/usr/bin/file` means something else, the flag to print a mime-type instead of the human-readable string from the magic file is `-I` (uppercase i). I'd propose a patch but I have no ideas offhand about how to handle this.

**Comment by leahneukirchen** [comment]
I think `file --mime` works on all systems (tried Linux, macOS, FreeBSD, OpenBSD).
