### ISSUE TITLE
Question: minc documentation is unclear

### ISSUE THREAD

**Issue by ngortheone** [leahneukirchen/mblaze#178]
Hi @leahneukirchen 

English is not my native language although I use it daily for many years now.  So my question may be due to some misunderstanding. I do apologize upfront in case my question is stupid:

`man 1 minc` says

> minc incorporates new messages in the maildir folders dirs by moving them from new to cur, and adjusting the filenames.

What does that exactly mean and what is the intended use case? What happens when a message is "incorporated"? It sort of reads as "mark message as read" in traditional sense, but I guess the specific choice of words in the manual was not accidental and probably means something else. Could you please elaborate?

Thanks

**Comment by leahneukirchen** [comment]
This is MH terminology originally, it means the mails are moved from "new" to "cur" but not marked as read.

Maildir delivers mail to new/ but most of mblaze only looks at cur/, so you need to move the mail between that to work with it later.

```
  3. To unite with, or introduce into, a mass already formed;
as, to incorporate copper with silver; -- used with with and
into.
```
