### ISSUE TITLE
Simply show an email body ?

### ISSUE THREAD

**Issue by sucrecacao** [leahneukirchen/mblaze#183]
Hello,

When running `mshow`, it also display a lot of other stuff, like the header etc..

How to only show the body ( text/html content ) part of a message ?

**Comment by leahneukirchen** [comment]
`mshow -h ''` will not print any headers, but still the empty line.

**Comment by sucrecacao** [comment]
That's pretty good still have a bit of noise, like the 
```
--- 1: multipart/mixed size=20441 ---
--- --- 2: text/html size=6072 ---
```
Any way to remove that ? or should I use some bash script ?
How maybe can you give me some pointer on the mshow source code to help me achieve this feature ?

**Comment by leahneukirchen** [comment]
Use `-N` to disable those.

**Comment by sucrecacao** [comment]
Thanks !
