### ISSUE TITLE
Attachment not found

### ISSUE THREAD

**Issue by Anachron** [leahneukirchen/mblaze#191]
I've accidentally added a wrong attachment path and sent the mail, now the recipient received a line with `# cannotopen (path)` which looks ugly.

Is it possible to mute errors like this or even prevent me from sending mails with attachments that cannot be read?

**Comment by leahneukirchen** [comment]
Hm, trying to reproduce this I get:

```
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="----_=_6cc04cbb64e51ce3738d8d8a_=_"

This is a multipart message in MIME format.

------_=_6cc04cbb64e51ce3738d8d8a_=_
mmime: error attaching file '/etc/issuez': No such file or directory

------_=_6cc04cbb64e51ce3738d8d8a_=_--
```

But status is 0, so this should be fixed and then reported (or even made fatal).

**Comment by Anachron** [comment]
Yep, I believe this should be a trivial fix? It not I can write a simple wrapper running "test -f".
