### ISSUE TITLE
Can mshow decode multiple parts at once?

### ISSUE THREAD

**Issue by guillaumecherel** [leahneukirchen/mblaze#197]
The man says

> mshow, by default, decodes all ‘text/*’, ‘message/rfc822’ and ‘multipart/*’ parts […]

But I can't get it to decode both the text/html and text/calendar at the same time.

I have an email that has the following parts:

```
  1: multipart/alternative size=7357
    2: text/plain size=206
    3: text/html size=2130
    4: text/calendar size=3227

```

and I set up the filters for text/calendar (just use `text/calendar: cat` for testing purpose).  Running `mshow -A text/plain:text/calendar` only displays the text part. Is there a way to make it display all parts at once? There is `mshow -O msg parts ...`, but it requires telling explicitly which parts to extract. I'm looking for a more automatic way.

**Comment by mbauhardt** [comment]
is here any solution? using `malternatives`?

**Comment by leahneukirchen** [comment]
As of 318ac214f you can use `-A all`.

**Comment by mbauhardt** [comment]
thx!
In the meantime I found `mless` in combination with `lesskey` to toggle between plain/html.

cool stuff!
