### ISSUE TITLE
Can mshow display multiple parts at once?

### ISSUE THREAD

**Issue by guillaumecherel** [leahneukirchen/mblaze#198]
The man says

> mshow, by default, decodes all ‘text/*’, ‘message/rfc822’ and ‘multipart/*’ parts […]

But I can't get it to decode both the text/html and text/calendar at the same time.

I have an email that has the following parts:

```
  1: multipart/alternative size=7357
    2: text/plain size=206
    3: text/html size=2130
    4: text/calendar size=3227

```

and I set up the filters for text/calendar (just use `text/calendar: cat` for testing purpose).  Running `mshow -A text/plain:text/calendar` only displays the text part. Is there a way to make it display all parts at once? There is `mshow -O msg parts ...`, but it requires telling explicitly which parts to extract. I'm looking for a more automatic way.

**Comment by leahneukirchen** [comment]
Interesting use case, this is not supported yet. I guess one could add a flag that renders all parts.

**Comment by guillaumecherel** [comment]
Thanks for your answer. I don't have time to work on it for the moment so I'm closing this issue. I got around with a script of my own calling mshow multiple times.
