### ISSUE TITLE
Save sent emails in a folder ?

### ISSUE THREAD

**Issue by stacyharper** [leahneukirchen/mblaze#210]
Hello there !

I'd like to keep trace of my sent emails. Common email app save them in the Sent imap folder. I think it should be the mblaze responsibility (probably not the msmtp on) but I may be wrong. Or maybe my provider responsibility but Migadu lacks this feature I think.

I'd like to know if someone got this feature and if so, how ? 
Is it something mblaze should/could do ?

Thanks a lot !

**Comment by leahneukirchen** [comment]
In mblaze-profile(5):

```
     Outbox:
             If set, mcom(1) will create draft messages in this maildir, and
             save messages there after sending.
```

If you sync this with your provider it probably does what you want.

But e.g. GMail (and Fastmail, if you enable it), feature saving all SMTP sent mails server side. This is outside of mblaze's control.

**Comment by Eluminae** [comment]
Oh ya. But as I use multiple maildirs and --read-envelope-from
--read-recipients. I should probably find another way :D

Thanks for pointing this out !
