### ISSUE TITLE
Reply change the current email ?

### ISSUE THREAD

**Issue by stacyharper** [leahneukirchen/mblaze#214]
Hello there,

I got a new question. As I mless my mails, I sometime reply to them. I'd like to continue my mless browsing where I left it but I'm pushed to the top and have to browse from start again.

I think thats because the cur symlink changed but I'm not sure.

Is it the expected behavior ? Can I change it ?

Thanks a lot !

**Comment by stacyharper** [comment]
Or maybe mrep will flag the cur mail as replied, wich mean a change in its file path ? Then mrep should also take care to fixup the seq and cur ?

**Comment by leahneukirchen** [comment]
Exactly, thanks for reporting.

**Comment by leahneukirchen** [comment]
Does that work for you?

```
diff --git a/mcom b/mcom
index 4c1027f..f1657ad 100755
--- a/mcom
+++ b/mcom
@@ -478,6 +478,9 @@ while :; do
 			*mbnc*) mflag -P -- "$1" ;;
 			*mfwd*) mflag -P -- "$@" ;;
 		esac
+		case "$0" in
+			*mrep*|*mbnc*|*mfwd*) mseq -f | mseq -S ;;
+		esac
 
 		exit 0
 		;;
```

**Comment by stacyharper** [comment]
Yes it does ! Good job ! :D
