### ISSUE TITLE
LESSKEYIN instead of LESSKEY ?

### ISSUE THREAD

**Issue by stacyharper** [leahneukirchen/mblaze#215]
Hello there,

gnu less seems to be using LESSKEYIN and not LESSKEY. I'm just discovering this aspect of less so I might be wrong. Or maybe this behavior changed over time ? If I'm right, we have to export LESSKEYIN instead in `mless`.

Thanks a lot !

**Comment by stacyharper** [comment]
Okay looks like you were relying on lesskey which is now deprecated cause less can read lesskey file directly. Maybe you could adapt this (and also add some documentation somewhere ?)

**Comment by leahneukirchen** [comment]
Well we can't go all-in on LESSKEYIN because it's only in the latest less releases... but I wonder why just setting LESSKEY doesn't work anymore? The manpage suggests so.

**Comment by stacyharper** [comment]
I dont know much. I just discovered setting up LESSKEY is not enough in
my context o_O

**Comment by stacyharper** [comment]
> Just to verify, do you have a `~/.lesskey` file?

No I dont

**Comment by leahneukirchen** [comment]
I think this should fix it. Move the file to .mlesskey if your less is new enough.

**Comment by stacyharper** [comment]
Yes that will works. Thanks again for those fast fixes !

Btw, I added personal exit code handling with dedicated less quit
commands. I think we could find a way to give the hand to the user.
Without requiring to fork all the script.
