### ISSUE TITLE
Unresolved entries in sequence with mthread

### ISSUE THREAD

**Issue by fagg** [leahneukirchen/mblaze#218]
Hello,

Firstly, thank you for mblaze. It's terrific.

I am however having a slight issue, which I cannot explain.

I am using isync to sync my mail to my laptop from my server which is running dovecot. I have verified that this occurs both locally and on the maildir that dovecot serves. 

Sometimes, I notice unresolved messages in sequences when I use mthread.

See this output, which was generated using this command:

> mlist -s $MAILDIR | mthread | mseq -S

You'll notice between 6 and 8, there is a weird entry in the thread that doesn't actually exist:

![mblaze-w-mthread](https://user-images.githubusercontent.com/1742468/142711808-e53f77e3-577a-4e8f-a0db-5763cfe87a61.png)

> moon$ mshow 7
> mshow: <CAKoxK+44JA+EtHk_FbLqh1RxfkCURs=mHDpyj61XJpWRwy-hfw@mail.gmail.com>: No such file or directory

But, when I omit mthread, and just run:

> mlist -s $MAILDIR | mseq -S

![mblaze-no-mthread](https://user-images.githubusercontent.com/1742468/142711816-a61102a2-0d70-4166-b6f9-a98022329aee.png)

I do not see this issue, and 62 messages in the sequence are shown correctly. In the first sequence, there's 62 valid messages but 63 total (if you assume the unresolved message counts).

Is this a bug or am I doing something wrong? Please let me know if there's anything else I can provide to help to resolve this.

Thanks!

**Comment by Duncaen** [comment]
This happens if there is a mail with "In-Reply-To" header to a message id that is not part of the mails passed to `mthread`.
Sequences that are not threaded don't look at the "In-Reply-To" header so they don't add those missing message ids.

**Comment by fagg** [comment]
Thank you for the explanation. That makes sense.
