### ISSUE TITLE
Are tests broken?

### ISSUE THREAD

**Issue by jgarte** [leahneukirchen/mblaze#221]
Hi are tests broken?

How can I run the tests?

Any advice is much appreciated.

**Comment by leahneukirchen** [comment]
Tests work fine on Linux (and OpenBSD last I tried), you need Perl installed and run `make check`. What happens for you?

**Comment by jgarte** [comment]
I thought they might be because of [this comment](https://github.com/guix-mirror/guix/blob/74130e73c019d7f2bc0700eca04d797d2645ffa4/gnu/packages/mail.scm#L2729) in the guix package for mblaze and the fact that the tests were disabled.

I enabled the tests in the guix package and saw that they were actually passing so the comment was lying.

I sent a patch to guix, enabling the tests:

https://issues.guix.gnu.org/54306

I'll close this issue. Thanks for confirming also/clarifying.

**Comment by leahneukirchen** [comment]
Perhaps it was related to this #200 which made tests fail in some CI situations. But is fixed now.
