### ISSUE TITLE
`mlist -s ~/mail/INBOX | msort -d | mscan` crashes my terminal.

### ISSUE THREAD

**Issue by jgarte** [leahneukirchen/mblaze#224]
`mlist -s ~/mail/INBOX | msort -d | mscan` fro the README crashes my terminal.

Any idea what might cause this or how to debug it?

**Comment by leahneukirchen** [comment]
mscan should escape all invalid UTF-8 uses, so this is interesting. Which terminal emulator is it?

**Comment by jgarte** [comment]
@leahneukirchen 

st packaged in void:

https://github.com/void-linux/void-packages/tree/master/srcpkgs/st

**Comment by leahneukirchen** [comment]
It's probably this long-standing st/Xft issue: http://git.suckless.org/st/file/FAQ.html#l224

To reproduce, try
```
printf '\xf0\x9f\x9b\x91\n'
```

Close the issue when this crashes st, it's not related to mblaze then. ;)

**Comment by jgarte** [comment]
> 

Yup, that was it! Thanks for helping me debug that. Much appreciated!
