### ISSUE TITLE
Request: Wiki or Cookbook

### ISSUE THREAD

**Issue by jgarte** [leahneukirchen/mblaze#227]
Hi wdyt of having a wiki or cookbook for using mblaze, sharing tips, tricks, and/or workflows?

Some things are scattered across blog posts and it would be nice to have a quickstart guide for getting productive with mblaze and doing basic things.

For example, how does one reply to an email or how do I continue composing a draft before I send it?

The above common task and others would be nice entries for a cookbook. Otherwise, the process feels quite slow for learning mblaze. Equipped with that basic knowledge, reading the man pages would be easier as a quick reference for new use cases and further learning.

**Comment by leahneukirchen** [comment]
I have opened the Wiki to all people with a Github account, feel free to use it. :)

> For example, how does one reply to an email or how to I continue composing a draft before I send it?

I think `mrep` should be discoverable from `mblaze(7)`, and if you started editing a draft with `mcom` you may find `mcom -r`. but ymmv.

**Comment by jgarte** [comment]
@leahneukirchen 

Thanks! 

Hopefully people who use mblaze regularly can share their tips and advice on it.

I'll try to add what I can given my knowledge of mblaze.
