### ISSUE TITLE
Needless awk evocations in mcom

### ISSUE THREAD

**Issue by readmemyrights** [leahneukirchen/mblaze#238]
At multiple points in mcom
awk is invoked in the middle of a pipeline
like this:

```shell
awk '{ print }'
```

In the context of a pipeline
it's basically a no-op,
it prints out every line as read,
performing no additional processing.

I'll send a pull request shortly,
unless this command does something more that I just don't notice.

**Comment by leahneukirchen** [comment]
This is intentional and an idiom to ensure the last line has a final newline.

**Comment by readmemyrights** [comment]
Thanks for the quick reply, it certainly does make sense
