### ISSUE TITLE
Separate Outbox and Draft

### ISSUE THREAD

**Issue by thyssentishman** [leahneukirchen/mblaze#240]
Hi,

this is a feature request. Would you consider adding a 'Drafts' profile key, so that one can specify where to store draft emails instead of saving them together with the sent emails? This would be useful to sync draft emails with the IMAP server so that one can continue writting the draft on another client e.g. on the phone. 

I'm aware that I could put together a script to move emails flagged as drafts to the desired folder before syncing, however I feel like the profile key would be a cleaner solution.

Thank you :)

**Comment by leahneukirchen** [comment]
It's a reasonable feature, yes. Wanna try a PR?

**Comment by thyssentishman** [comment]
What do you think? :)

**Comment by thyssentishman** [comment]
Thank you! :)
