### ISSUE TITLE
New tag?

### ISSUE THREAD

**Issue by Anachron** [leahneukirchen/mblaze#251]
There has been quite a lot of changes in the last 2 years, some interesting new features as well.

Can you create a new tag and push it on `void-packages`? Thanks!

**Comment by sansfontieres** [comment]
That would be brilliant for nixpkgs too 😋

**Comment by leahneukirchen** [comment]
Yes yes, soon!

**Comment by Anachron** [comment]
When exactly is this "soon"? ;-)

**Comment by leahneukirchen** [comment]
c087993
