### ISSUE TITLE
Using mrefile with xargs

### ISSUE THREAD

**Issue by lechner** [leahneukirchen/mblaze#262]
Hi,

Thanks for these nifty utilities!

Would it be advantageous to swap the arguments to `refile` so that the target folder comes first (or provide a command line option) for easier use with `xargs`?

Kind regards
Felix Lechner

**Comment by leahneukirchen** [comment]
If you just pass one argument, `mrefile` reads mail names from stdin and moves them to that dir, so you don't even need xargs.

**Comment by lechner** [comment]
Okay, thanks!

Closing.
