### ISSUE TITLE
'mrefile' demands ~/.mblaze/seq

### ISSUE THREAD

**Issue by lechner** [leahneukirchen/mblaze#263]
Hi,

I upgraded recently. Now `mrefile` exits with this message:

```
could not read sequence '/home/lechner/.mblaze/seq': No such file or directory
```

What should I do, please? Thanks!

Kind regards
Felix

**Comment by leahneukirchen** [comment]
You can ignore this warning if you don't use sequence numbers, or silence it by creating an empty file `~/.mblaze/seq`.

**Comment by lechner** [comment]
Thanks! Is it just a warning? I did not see any paths with `-v`.

**Comment by leahneukirchen** [comment]
yes, just a warning when the sequence parser starts (tho I thought that would be delayed until it's necessary hrm)

**Comment by lechner** [comment]
I am stunned.  I don't think any files are being copied even when I create a dummy `~/.mblaze/seq`.

**Comment by leahneukirchen** [comment]
Please post the commands you are actually running, my 🔮 is out of order.

**Comment by lechner** [comment]
Hi, I ran
```
for file in * ; do mrefile -v $file /home/lechner/Maildir-private/.Archive/ ; done
```
in Bash, but I renamed the files manually and moved them.  Maybe we can figure it out next time.

Thanks for the nice utilities!

**Comment by leahneukirchen** [comment]
Ah, you need to write `./$file`, since mblaze needs a `/` to detect a maildir file as file.

**Comment by lechner** [comment]
What else would it be?
