### ISSUE TITLE
Manipulate cur in mscan (like in mless)

### ISSUE THREAD

**Issue by rnkn** [leahneukirchen/mblaze#268]
Hello!

Thank you for such wonderful software! It's such a joy to use :)

I have a feature request. I don't know how complicated it might be.

I would like to be able to navigate around `mscan` the same way I can in `mless`, and for this to change the current `cur`. It's essentially duplicating the exact functionality of `mless` but without the message preview.

What do you think?

**Edit**: `cur` not `seq`

**Comment by leahneukirchen** [comment]
you can use `mseq -C` to update the cur, e.g. `mseq -C +` to go to the next message etc.

**Comment by rnkn** [comment]
I mean from within `mscan`, like with `[` and `]`. Or is there some trick to this I'm not seeing?

**Comment by rnkn** [comment]
Turns out what I wanted was `MBLAZE_PAGER=cat` (then `mseq -C`). Thanks!
